### ISSUE TITLE
Edit armor stands dont work on 1.21 Purpur

### ISSUE THREAD

**Issue by shawn695** [Zrips/CMI#9283]
### Description of Issue

when you try to edit a armor stand it gives u a message sayings someone else is editing it
![image2](https://github.com/user-attachments/assets/5708de7d-7ec2-41e4-85c5-d3bf76089fb5)

### Version Information

```shell
09.11 00:33:59 [Server] INFO CMI: 9.7.7.8 Velocity CMIB  SqLite
09.11 00:33:59 [Server] INFO CMILib: 1.5.2.2 
09.11 00:33:59 [Server] INFO Server: Purpur(2284) 1.21-R0.1-SNAPSHOT-
09.11 00:33:59 [Server] INFO CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled 
09.11 00:33:59 [Server] INFO Modules -> 65 enabled 2 disabled: tablist, votifier
```

### Errors

```shell
08.11 23:52:43 [Server] WARN [CMI] Task #765596 for CMI v9.7.7.8 generated an exception
08.11 23:52:43 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIAttribute
08.11 23:52:43 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Modules.AStand.ArmorStandManager$26.updateLooks(ArmorStandManager.java:1085) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:43 [Server] INFO at CMILib1.5.2.2.jar/net.Zrips.CMILib.GUI.CMIGui.addButton(CMIGui.java:252) ~[CMILib1.5.2.2.jar:?]
08.11 23:52:43 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Modules.AStand.ArmorStandManager.openDelayedEditor(ArmorStandManager.java:1090) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:43 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Modules.AStand.ArmorStandManager.lambda$1(ArmorStandManager.java:647) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:43 [Server] INFO at CMILib1.5.2.2.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtEntity$3(CMIBukkitImpl.java:158) ~[CMILib1.5.2.2.jar:?]
08.11 23:52:43 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:43 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
08.11 23:52:43 [Server] INFO Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IncompatibleClassChangeError: Method 'org.bukkit.attribute.Attribute[] org.bukkit.attribute.Attribute.values()' must be Methodref constant [in thread "Server thread"]
08.11 23:52:43 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Containers.CMIAttribute.<init>(CMIAttribute.java:24) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:43 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Containers.CMIAttribute.<clinit>(CMIAttribute.java:12) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:43 [Server] INFO ... 13 more
08.11 23:52:46 [Server] WARN [CMI] Task #765766 for CMI v9.7.7.8 generated an exception
08.11 23:52:46 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIAttribute
08.11 23:52:46 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Modules.AStand.ArmorStandManager$26.updateLooks(ArmorStandManager.java:1085) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:46 [Server] INFO at CMILib1.5.2.2.jar/net.Zrips.CMILib.GUI.CMIGui.addButton(CMIGui.java:252) ~[CMILib1.5.2.2.jar:?]
08.11 23:52:46 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Modules.AStand.ArmorStandManager.openDelayedEditor(ArmorStandManager.java:1090) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:46 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Modules.AStand.ArmorStandManager.lambda$1(ArmorStandManager.java:647) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:46 [Server] INFO at CMILib1.5.2.2.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtEntity$3(CMIBukkitImpl.java:158) ~[CMILib1.5.2.2.jar:?]
08.11 23:52:46 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
08.11 23:52:46 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
08.11 23:52:46 [Server] INFO Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IncompatibleClassChangeError: Method 'org.bukkit.attribute.Attribute[] org.bukkit.attribute.Attribute.values()' must be Methodref constant [in thread "Server thread"]
08.11 23:52:46 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Containers.CMIAttribute.<init>(CMIAttribute.java:24) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:46 [Server] INFO at CMI-9.7.7.8.jar/com.Zrips.CMI.Containers.CMIAttribute.<clinit>(CMIAttribute.java:12) ~[CMI-9.7.7.8.jar:?]
08.11 23:52:46 [Server] INFO ... 13 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CyanB1t** [comment]
Same exact error, we're running:
CMI 9.7.7.7
CMILib 1.5.2.2
Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

So far I've gathered that this issue isn't affecting non-op's and users who don't have the permission node cmi.command.armorstand.scale. I've done some testing and this seems to be the only permission that generates the exception.

**Comment by Zrips** [comment]
fixed with latest update
