### ISSUE TITLE
CMI not working on 1.8.8

### ISSUE THREAD

**Issue by Zenya4** [Zrips/CMI#2652]
**Description of issue or feature request:**

I am facing an issue where CMI will not run on a 1.8.8 PaperSpigot server. According to the tested versions, 1.8 should be supported. However, I am getting an error on startup and the plugin just disables itself
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
> [10:59:39 ERROR]: Error occurred while enabling CMI v8.6.17.4 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Material.isItem()Z
at com.Zrips.CMI.Modules.CmiItems.ItemManager.load(ItemManager.java:76) ~[?:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1285) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [10:59:39 INFO]: [CMI] Disabling CMI v8.6.17.4
```

---

**Cmi Version (using`/cmi version`) CMI v8.6.17.4:** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)**

**Comment by the456gamer** [comment]
A recent update changes a method to a newer one (I think, anyway) that was not present in older versions.

```Fix for scary but harmless errors appearing with latest 1.15.1 builds on server startup```
This is the update/method that changed it. (Again, only guessing)

**Comment by Zrips** [comment]
Will get fixed. And yea @the456gamer is correct on which change caused this error.
