### ISSUE TITLE
CMI an Denizen have a Problem ?

### ISSUE THREAD

**Issue by XxDuckbusterxX** [Zrips/CMI#1694]
If I install the plugin Denizen v1.0.4-SNAPSHOT (build 1673-REL). Then everything works normally. The plugin is loaded and still no errors occur. As soon as I insert a script and reload Denizen. Then the console throws out the bugs (see below). The error happens only when logging on to the server. I do not spill on the spawn point but where I logged off.
You can see it  off-> [13:40:32 INFO].... 
What can this be? CMI and Denizen may not work together? It would be a pity, because I could use my own scripts.

---

```
[13:38:39 ERROR]: Could not pass event InventoryClickEvent to Denizen v1.0.4-SNAPSHOT (build 1673-REL)
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at net.aufdemrand.denizen.objects.dInventory.mirrorBukkitInventory(dInventory.java:71) ~[?:?]
at net.aufdemrand.denizen.scripts.containers.core.BukkitWorldScriptHelper.inventoryClickEvent(BukkitWorldScriptHelper.java:363) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
... 15 more
[13:38:41 INFO]: Duckbuster1983 lost connection: Disconnected
[13:38:41 INFO]: Duckbuster1983 left the game
[13:40:32 INFO]: UUID of player Duckbuster1983 is 4ab3ce4f-98a4-4340-afb8-a4949c7277f7
[13:40:32 INFO]: Duckbuster1983[/37.201.119.150:32276] logged in with entity id 670 at ([Spawn]-949.7756541123009, 7.0, -57.49542036372137)
[13:40:32 WARN]: [CMI] Task #1378 for CMI v8.6.1.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.isChunkGenerated(II)Z
at com.Zrips.CMI.Modules.tp.Teleportations.isEmpty(Teleportations.java:545) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:641) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:395) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:283) ~[?:?]
at com.Zrips.CMI.AllListeners.PlayerListeners$6.run(PlayerListeners.java:766) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-2086bb0-1988d7f]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-1988d7f]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

---

**Cmi Version (using`/cmi version`):** 
CMI v8.6.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):** 
Denizen v1.0.4-SNAPSHOT (build 1673-REL)

**Comment by Zrips** [comment]
This will be fixed with todays update

**Comment by XxDuckbusterxX** [comment]
Hello, I have now changed to the CMI version 8.6.1.2 and now the error occurs again.
Everything works fine in version 8.6.1.1.

```
[07:56:13] [Server thread/WARN]: [CMI] Task #318 for CMI v8.6.1.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.ChunkSnapshot.getData(III)I
	at com.Zrips.CMI.Containers.CMILocation.getBlockCMIType(CMILocation.java:166) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.isEmpty(Teleportations.java:550) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:592) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:396) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:311) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:284) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners$6.run(PlayerListeners.java:788) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
